### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Dpbm** [Dpbm/home-server#2]
# TODO

- [x] setup vnc (add password)
- [x] setup ssh (key only)
- [x] setup rkhunter
- [ ] add readme
- [x] deactivate bluetooth by default
- [ ] auto updates
- [x] add jellyfin
- [x] config external HD
